---
title: Development Economics & Government Policy
author: written by Sauhaard Poudel
geometry: margin=1.5cm
output: pdf_document
---

\tableofcontents

\newpage
# Introduction To Economic Development

## What Is Economic Development?

### Sen's Definition:
1. Improving peoples well being and quality of life, this involves improvements in the standards of living.
2. Reductions in poverty and improved health/ education.
3. There must be high levels of freedom and economic choice.


### Todaro's Definition:
1. Availability and distribution of life sustaining goods, such as food, shelter and health
2. An increase in standards of living
3. Expansion and economic and social choice


Development is a normative concept, and we cannot define it neatly.

# Economic Growth vs Development

Growth does not equal development. Just because there is high GDP growth, that doesn't mean the country/ economy is developing.

## Why Is Growth Good For Development?
Health, jobs and infrastructure are the big drivers of development.

1. This leads to higher incomes
      * Better jobs and better quality of life as they can afford more material goods
      * Income inequality may go down
   * A reduction in poverty for people in the economy
2. Firms will make higher profits
     * Firms will have more confidence in the economy
       * This leads to them hiring more people
       * Make greater sales as the economy grows
       * If they reinvest their higher profits into research and development, that can lead to innovations in technology
         * This allows the economy to move away from the agriculture sector and help advance the economy (such as moving away from agriculture and moving to service sector)
     * High job creation as firms will want to employ more people to meet their demands (due to economic growth)
3. Fiscal dividends: Higher fiscal revenues for the government
     * The government can then spend money on things such as infrastructure and help develop the economy even further 

## Evaluation Of The Importance Of Growth For Development

1. There is no guarantee that growth will be distributed equally
     * This means that the standard of living has not increased for all people
     * Income inequality may hinder development as most of the money may be going to a small number of people
2. Negative externalities and problems with sustainability arise from growth
     * In the short run this is great for growth, but in the long run, the resources will disappear thanks to unsustainable growth
       * Without these resources then, the economic growth will not consistently grow, and the future generations will suffer
     * Also pollution from growth reduces the people's living standards in the economy
       * This is a drag on the economic development of a country
3. Is the growth just in one sector?
     * If the growth is happening in 1 sector, this is not going to help develop the entire economy.
     * Such as Nigeria, they have a massive oil sector that drives most of their GDP, but that doesn't mean that money is being spread around to the rest of the economy

Inclusive growth (growth for everyone) is **good**, but noninclusive growth is not.
Growth is necessary but *not* sufficient on it's own to make a country more economically **developed**. 

# Common Characteristics Of Developing Countries

## What Commonalities Do Developing Countries Share?

1. Low standards of living
     - Low incomes
     - High poverty
     - Bad job creation
2. Low levels of productivity
     - Lack of investment
     - Lack of capital, and lack of availability of capital
     - This means very low productivity
3. Low level of savings means they are trapped in very poorly paid jobs, meaning the chances of getting out of the poverty trap is very low
     - Lack of education on where to save and how to save the money
     - They may not even have money to save as they are on such low incomes
4. High population growth  
     - People tend to give birth to lots of children because the children are made to work in the farm to help the family
5. Primary sector dependence
     - Agriculture is normally the largest sector of the economy
     - These countries tend to be well endowed with natural resources
       - This means they put all of their factors of production in producing/ extracting those natural resources
     - But due to low productivity and poor capital, this doesn't necessarily mean they will have very much economic growth
6. Incomplete markets: Not all of necessary market forces are there
     - Lack of property rights
     - Their currencies tend to not be very strong, countries don't really want their money
7. High unemployment/ underemployment
     - High unemployment is due to the fact that the agricultural sector is dominant, which has low productivity
     - Low savings means there is not a lot of investment
       - Low capital
     - This hinders employment as it becomes very difficult to find one as there is not a lot of investment
     - Those that do find jobs can find themselves underemployed
     - There may even be a lot of people that do not want to be employed
       - This is the hidden unemployment of the economy
       - This means that the real unemployment rate may even be higher than what it is currently shown as
  
8. Low economic power on the international stage
     - This means they cannot fight trade wars
     - They don't have much of a say internationally
     - They can't ask about finance very easily
     - Ultimately, they cannot get their voice across in the international stage

## Evaluation:

1. Not all developing countries will have the same number of characteristics
2. Different countries will have different political structures, different cultures, different friends, etc.



# Measures Of Economic Development

## Single Indicators
These are indicators that look at just 1 thing.

### GDP Per Capita
  - This is the average income per person in the economy.
  - GDP doesn't tell us about negative externalities, pollution, income inequality, etc.
  - What we tend to use instead of GDP/Capita is Gross National Income
    - GNI looks at the income generated by all of the country's factors of production regardless of the location
    - Labour is a classic example, people from a country may leave and work abroad, but then they send money back home
    - A lot of the money tends to be repatriated
    - Also, developing countries can attract lots of FDI
      - But a lot of the money made by the TNC's tend to be repatriated back into the TNC's home country
  - If we use either GNI or GDP/capita, we want to have them in terms of Purchasing Power Parity
    - This allows us to have better comparisons between the standards of living in each country
    - This is because different countries have different prices for goods and services, so adjusting for PPP is good
  
### Health Of People In The Economy
 - Such as: Life expectancy, and infant mortality
 - Improvements in health imply:
   - Increasing life expectancy implies that the health care treatment is getting better in the country
   - Also means that there are lots of doctors, implying that there are lots of jobs for higher skilled people
   - Doctors need to go to higher education so it also implies that the education in the country is improving
   - Sanitation may be another thing that is improving in the economy to allow people living longer
   - Access to hospitals may be very high
   - Education on prevention of these diseases may also be very high
  
### The Education Of People In The Economy
 - Such as: Adult literacy and enrolment in primary education
 - Improvements in education imply:
   - That educational institutions are strong
   - There are teachers getting jobs to educate people
   - Potential for higher skill jobs improves
   - Number of people that can do higher skill jobs improves
     - This leads to lower unemployment
     - Leading to higher incomes for the country

## The Human Development Index (HDI):

The HDI is a measure of economic development calculated by the UN. 
It is an example of a ***composite index***.

It is calculated using these 3 factors:
1. Life expectancy
2. The mean years of schooling of adults that are 25 years old + and the expected years of school a typical five year old will go through
3. Income measured by the **Gross National Income per Capita** of the country. 

 The higher the HDI, the greater the development.

### Advantages Of Using HDI: 
1. Takes multiple different variables into account
2. Easy to calculate because governments already collect the data required to calculate the HDI

### Disadvantages Of Using HDI:
1. Quality of life and quality of education is not factored in
    - Someone may have a long life but terrible health
    - Someone may have many years of education but the education was terrible
2. There is no consideration of income inequality
   - The GNI per capita may be high but most of the income may be going to a few number of people
3. There are other very crucial factors to look at when examining development, such as levels of freedom and state of the environment

However, since HDI is only an indicator and not a precise measure, it should not be expected to be perfect.


## Other Indicators:

### Inequality Adjusted Human Development Index (IHDI):

This is an adjustment of HDI which includes inequality as the 4th indicator.

### The Multidimensional Poverty Index (MPI):
- This measures the percentage of the population that is multidimensional poor. 
  - It uses data for health, education and standard of living but uses a broader range of indicators within these categories.
- It highlights the countries where some people are extremely rich, but the majority is not.
- The **problem** with this measure is that the data required to calculate it may not always be available, it also does not take into account the environment.


# Factors Influencing Growth and Development

## Economic Factors

### 1. Primary Product Dependency:

Primary products are goods such as commodities and raw materials.

Having an economy that is dependent on primary products causes problems for the following reasons:

- Natural disasters can wipe out the production plants of primary products (such as crops)
   1. This means there will be no production
   2. No production means no income generated
   3. No income leads to standards of living dropping
- Primary products tend to have a ***low*** Income Elasticity of Demand (YED).
   1. This means primary products are *inferior*, or *normal* goods, so as incomes of people go up, their demand for primary products don't go up very much
   2. Instead, their demand for manufactured goods increases, this is because manufactured goods are likely to be luxury goods as they are not necessities
- The ***Prebisch Singer hypothesis*** suggests that the **long run price** of primary goods **declines** in *proportion* to manufactured goods.
      - This means as the price of manufactured goods go down, the price of primary products go down also
      - But this has shown to be false in certain circumstances, the prices of primary products such as oil has increased over the last few decades while the price of manufactured goods has decreased (thanks to Chinese exports).
- Dutch disease is another big problem
   1. This is when a country starts exporting lots of their primary goods in a short amount of time, leading to the appreciation of their currency
   2. This is because as demand for their exports increase, the demand for their currency also increases
   3. As the currency appreciates, their exports become more and more expensive internationally
   4. This leads to decreased price competitiveness throughout the economy, and causes a fall in output for certain industries.
      - This occurred for the non-oil sectors in Nigeria.

Some countries have managed to develop using their primary product dependence, such as Saudi Arabia.

### 2. Volatility of Commodity Prices

Primary products tend to have inelastic demand and supply curves, which means small changes in either demand or supply lead to huge fluctuations in price.

- These changes mean that producers have very unstable incomes.
  - Instability means it is difficult to plan for the future and therefore it is difficult to make long term investments
  - Another problem for producers is that their incomes may shrink rapidly thanks to volatility of commodity prices, which can then lead to poverty and a much lower standard of living
- When prices of commodities rise for a number of years, this just tends to be increases in price thanks to over-investment. 
  - This over-investment then pumps up the price and when the investment money is no longer flooding in, it causes the commodity prices to fall, which leads to problems as mentioned earlier

### 3. Savings Gap

1. Developing nations tend to have low incomes due to unemployment/ under-employment
2. This ultimately means they are not saving as much as the *marginal propensity to save* is quite low when incomes are also low
3. Without people saving, banks don't have a lot of money to lend out to firms for investment
4. Without investment, technological innovation and capital accumulation is vastly slowed down, which results in the economy having very low productivity (no capital machinery), and low productivity leads to very low economic output
   1. Another point to make is that the *long run aggregate supply* curve will be at a very low output
   2. This means the economy cannot produce very much at max capacity
   3. If demand increases without the *long run aggregate supply* increasing (it only increases when the quality or quantity of factors of production in the economy increase), then this leads to high rates of inflationary growth.
   4. Inflationary growth is terrible as it raises price levels very high without also increasing output very much.

The savings rate in Africa is around 17% of the GDP.

The **Harrod-Domar model** of growth suggests that savings provide the funds which are borrowed for investment purposes.

- This means the rate of growth for a country is based on the level of savings it has
- The model concludes that economic growth is down to the amount of labour and capital in an economy
  - Developing nations tend to have a lot of labour available, so their growth must be hindered by the fact that they don't have any capital
  - Therefore, in order to accumulate capital:
    1. Investment is required to buy capital
    2. Investments are funded by banks, banks need money to lend out
    3. Banks get their money from deposits
    4. Deposits are given into the bank in the form of savings
    5. Therefore savings are required to start the chain towards economic growth.
- However, there are some criticisms of the model:
  1. Economic growth is not economic *development*, meaning living standards may not rise (which is the main goal).
     - So if living standards don't rise, then it is not a very effective model to help development
  2. It is very difficult to save when you don't have any money. This is the case for people in poor countries, with a terrible job.
  3. Savings can lead to increased investments, but investments may not always lead to growth. This is because the money may be wasted or ineffectively spent.    


### 4. Foreign Currency Gaps

A foreign currency gap occurs when a country does not have the required amounts of foreign currency reserves to be able to purchase capital from abroad.

- The reason capital is normally bought from abroad is that developing nations tend to not have specialist capital inside of their countries
- Therefore they have to import it from abroad to get specialist capital and increase their productivity and output
- The gap can be caused by low exports relative to imports. 

A country that suffers from a foreign currency gap is Ethiopia.

- In 2018 their public debt was 60% of GDP
- Most of the debt has to be paid in foreign currencies and not their own.
- This means it is likely they do not have enough foreign currency to pay off their debt.

### 5. Capital Flight

Capital flight is when large amounts of capital is moved out of the country and sent elsewhere instead of being used there. This means there is less capital stock in the economy.

A good example of capital flight is money. Let's use a real life example:
  1. Money is moved out of Argentinian banks in 2001
  2. Banks without money cannot give out loans, or even give out cash to those that want to withdraw
  3. Everyone realises that money is running out and so they rush to withdraw, this is called a bank run
  4. The bank doesn't have enough liquidity to give out, leading to a crisis and people lose faith in the system

So why does capital flight occur?

1. People lack confidence in the country's stability or financial systems
2. People want to hide it away from the government, maybe for tax reasons.
3. TNC's may want to repatriate their profits in their home countries, so they send money back.

### 6. Demographic Factors

1. Developing countries tend to have higher population growth.
   - 5% population growth a year means the economy also has to grow by 5% a year to maintain living standards in the economy
   - This ultimately means that developing countries need higher rates of growth to develop compared to developed countries with lower birth rates
2. The high population growth is caused by high birth rates.
   - High birth rates means more children, children are "dependants".
   - More dependants mean less money for everyone as they need to support the dependants.
   - More children also means strains on schooling and education
   - Youth unemployment may increase, leading to negative social impacts with negative externalities, such as crime.

The population of Africa is expected to more than double by the year 2050.


### 7. Debt

1. Developing countries in the 1980's received huge loans from developing nations
2. Now they suffer from the massive interest repayments
3. This means they have less money to spend on the public sector
4. To finance the debt they may have to raise taxes, which will reduce consumption 
5. This will hinder growth even more.

Nigerias debt is 52% of their GDP.

### 8. Access To Credit And Banking

1. Developing nations have a very limited access to credit and banking
2. This means they cannot get loans to finance investment projects to try stimulating/ expanding the economy
3. A problem in developing nations is that people have to resort to *loan sharks* for loans, which is dangerous and may leave individuals permanently in debt.


### 9. Infrastructure

1. Low levels of infrastructure make it difficult and raise the cost of production for firms
2. This is because the cost of transportation increases as roads are not good and so longer routes may have to be taken
3. Terrible transport links mean the movement of goods may be disrupted very suddenly
4. This means foreign firms are less likely to invest and set up in your country, and the firms already in your country will have a much harder time expanding


### 10. Education And Skills

1. Poor education within these countries mean workers have very little skills
   - This means they will not be very productive either
   - Low productivity stunts economic growth as it means the LRAS of the economy will not be very high
2. However there is a problem with *over-education*, this is when graduates from university are unable to find graduate level jobs and so they have to take other, unskilled ones.


### 11. Absence Of Property Rights

1. Property rights are essential as individuals need to feel as if their assets are safe
2. High levels of property rights mean investors are not afraid of their assets being taken or stolen, making them more likely to invest into the country
  
A country where there was poor property rights is Zimbabwe, the country took away the farms and land of many farmers and this eventually lead to economic collapse, as well as mass starvation in the country.


## Non Economic Factors

### 12. Corruption

Many developing countries suffer from **corruption**, this means politicians and people in power are maximising their own welfare while disregarding the country's welfare.

1. This could arguably be another example of the principal agent problem.
2. Corruption is linked with having high levels of bureaucracy
   - If there is a lot of government control over the country then more people are needed to manage everything (bureaucrats).
   - Having more bureaucrats leads to an increased likelihood of corruption

### 13. Disease

Countries with high levels of HIV/AIDS, or malaria have a very difficult time developing. 
1. This is because a lot of the potential workforce are not able to work as they are not healthy.
2. A lot of money also has to be spent on medical care (if they can afford it).
3. If they are working then their productivity will be low as they are sick
4. Also, having a lot of ill people in the economy means there are a high number of dependants in the economy
   - This means more money is spent taking care of the dependants
   - This reduces the amount of money saved in the economy
   - Low savings lead to low investment, and makes economic growth more difficult.

### 14. Poor Climate

Countries with very harsh/ poor climates will find it difficult to grow the economy.

1. This may be because farmers cannot set up farms there
2. Another reason is that there may be a high likelihood of natural disasters
   - This puts off foreign investors as natural disasters can lead to their investment being ruined

### 15. Civil War

Civil war causes:

1. Political instability
   - This leads to investors thinking the country is too unstable to invest in
   - Investors want very stable government so that they can plan for the future and in the long term
2. War destroys infrastructure
3. High levels of poverty
4. Disease tends to spread during war time

\newpage

# Measures Of Income Inequality

## The Lorenz Curve

- The further the Lorenz curve is from the line of perfect equality, the more unequal the distribution of income is.

\vspace{0.6\textheight}


## The Gini Coefficient

- The Gini coefficient takes the Lorenz curve and gives us a numerical measure of the income inequality in the country.
- 0 means **perfect *equality***
- 1 means **perfect *inequality*** \

**The equation for the Gini coefficient:** \begin{huge} $\frac{SectionA}{SectionA + SectionB}$ \end{huge}

\newpage

# The Poverty Cycle

**Absolute poverty is when** someone is living with an amount of money below a certain threshold.

**Relative poverty is when** someone is living with money that is below the average.

**Why are people in poverty?**

1. A lack of opportunity for jobs in an economy
2. Lack of skills
3. Lack of education

## The Economic *Growth* Poverty Cycle:

\vspace{0.30\textheight}

1. **Low incomes in the economy**
2. This means that there is going to be a **low level of savings**.
   1. This may also be due to a lack of financial institutions in the economy
3. Low level of savings leads to a **low level of investment**.
4. Without investment there will be **low economic growth**.
5. Low economic growth means *low incomes*, and the cycle repeats.

## The Economic *Development* Poverty Cycle:

\vspace{0.30\textheight}

The development poverty cycle stems from the *growth* poverty cycle.


1. There are **low incomes** thanks to the growth poverty cycle.
2. In a country with *low incomes*, it is **hard for the government to fund education and health**
   1. This means people will have to pay for education and health *at the point of consumption*, and since there are low incomes, a lot of people may not be able to afford it.
3. This then leads to **low levels of human capital** in the economy.
   1. This essentially means workers have very low levels of skills.
4. If people do however find jobs, there will still be **low levels of productivity**.
   1. This is due to bad training and low level of skills.
   2. Low productivity then leads to low incomes, and then the cycle starts again.

# Policies To Redistribute Income & Wealth

## Taxation


1. Government can implement **progressive taxation** policies.
   - This is when higher income individuals are taxed more than lower incomes.
   - This can either be done by increasing the *non taxable income allowance* for lower incomes, or increasing taxes for richer incomes and then spending it on redistributitive policies, such as increased educational spending.
2. The government can reduce regressive taxation, such as VAT, cigarette duty and alcohol duty.


**Problems with those tax policies:**

1. Increasing taxes on the rich may actually result in **lower tax revenues**.
   - This is thanks to the Laffer curve.
2. Also, **regressive taxes are a big portion of total tax revenue**, so reducing them may lead to the government implementing austerity measures.


## Increased Transfer Payments

- The government can increase **welfare benefits** for people on lower incomes.

**What are the problems with increasing transfer payments?**

- It may **create disincentives** to work
  - This is because if people's benefits go once they start working, then it may lead to them not wanting work.
- Increasing transfer payments is **very costly**.


## Minimum / Maximum Wages

- **Minimum wages** allow lower income individuals to boost their incomes, and therefore have a better standard of living.
- **Maximum wages** may be placed to stop massive amounts of money going to a single person. This would reduce income inequality.

**What are the problems with min/max wages?**

1. Maximum wages create disincentives to be entrepenurial.
2. Minimum wages create unemployment in the economy.
3. Minimum wages also can create inflation in the economy as costs of production will rise.


## Legislation

- Anti **discrimination laws** can be introduced.
- Legislation to make it **harder to fire workers**.
- **More maternity/ paternity** leave.

**What are the problems with these legislative policies?**

1. They become **very costly for businesses**.
2. **Enforcing the policy** may be very costly.
3. There may be **government failure** if the government implements very very costly rules, causing businesses to shut down.
   - The businesses may even move out of the country.

## Improving Health Care & Education

These policies target the root cause of low incomes, which is poor productivity.

- Government spending on education and training can help boost productivity by giving workers new skills.
  - This increases the workers *marginal revenue product*, leading to higher incomes and wages.
- Improving health care increases productivity because less people will become sick.


**What are the problems with improving health care/ education?**

1. They are **very costly**.
2. These policies take a **long time to come into effect**.


## Evaluation

Here are some general evaluative points regarding the distribution of incomes.

1. Does the policy create disincentives to work?
2. Are the costs of the policy worth the benefits?
3. Is fairness more important than efficiency?
   - A lot of these policies are inefficient, such as maximum wages. They distort the market mechanism and are allocatively inefficient.
4. "Fairness" is a normative judgement, is it actually fair to tax workers with higher productivity?
5. What is the scope of government failure when implementing these policies?
  - A minimum wage that is too high can lead to very adverse effects.
6. Is the level of inequality that bad? Do we really need to intervene?


# The Laffer Curve

**What did Arthur Laffer say?** Laffer's idea was that increasing taxes will increase tax revenue up to a point. After this point, tax revenue's will start decreasing.


**The Laffer Curve Diagram:**

\vspace{0.35\textheight}

- The highest point is called the **efficient tax rate**.

**Why does tax revenue decrease after "_t_" ?**

1. There will be **disincentives to work harder**/ be entrepeneurial.
   - They may feel as if there is no point in working harder if all of their earnings will be taxed anyways.
2. People will **emigrate away** from the country.
  - Tax rates are lower in other economies, so people will just move away.
3. **Tax evasion** and tax avoidance.
  - Tax evasion is when you don't declare all of your income, and therefore don't have to pay taxes on what you haven't declared.
    - Tax evasion is illegal.
  - Tax avoidance is finding loopholes in the system to not pay as much tax.
    - Tax avoidance is completely legal.




# Strategies & Policies That Influence Development & Growth

## Institutional Factors

### 1. Education

**Why are improvements to education likely to boost development and growth?**

1. Education leads to **high productivity**, which promotes development
2. The more educated people there are, the higher the chance they are going to be in **better paying jobs** and have higher incomes
  - This means they can afford to purchase more material goods for their family, making them more well off
  - More education also leads to increase levels of social and economic choice, which according to Sen and Todaro is integral to economic *development*.
3. **Educating women** also promotes higher levels of development as they are more responsible, and more willing to purchase merit goods such as better education for their children, which in the long run will help development much more.
4. **Health benefits** can also be bought about by educating people on health risks such as HIV, which may be a reason for the lack of development in the country.
   1. Another thing to educate people on is contraceptive usage, this will prevent the spread of things such as HIV and also help *reduce* the rapidly growing populations.
5. **Technological advancements** can also be bought about by educating people, as then they have knowledge and can create new technologies in the economy.

**But the problem with using education as a policy to promote development is:**

1. There are issues with *funding*, education tends to be very expensive.
   1. If the government were to allow private education however, then there's the moral dilemma of whether it is fine for children to be discriminated against because of the amount of money they can pay.
2. There may be some underlying issues in society that make education ineffective
   1. One example of this may be that when children grow to a certain age, they may be expected to leave education and help support their family by taking up a job
      1. Therefore in some countries we may see a lot of primary school enrolment but little to no high school enrolment.


### 2. Health Care

**Why is good health care important to development and growth?**

1. The healthier people are, the more **productive** they will be
2. The more **jobs can be created** in the economy if there are lots of hospitals, GP's and dental practices.
3. **Standards of living will increase** as people are healthier
   1. Healthier people also tend to be *happier*, which is very important for the economy as happier people tend to be more productive also.
4. It also implies **better sanitation** and **cleaner drinking water**.
   1. These are all indicators that development is occurring in the country and people's lives are being improved.

**But the problem with trying to improve health in the economy is that**

1. There may be a *lack of funds* available to allocate to health facilities.
2. If the private sector gets involved with health care (which eliminates the problem of a lack of funding), is it really fair that people can be *declined health care* because they cannot pay the prices?

### 3. Infrastructure

Infrastructure is key to economic development and growth.

**Why is good infrastructure important to development and growth?**

1. Good infrastructure means **markets will be available**.
   1. This is because good infrastructure allows markets to come together, an example of this is *roads*.
   2. Without any roads in the UK, goods cannot be delivered to buyers.
2. Another great effect of good infrastructure is that **access to schools and hospitals** will become better.
   1. This allows sick people to get to a hospital quicker, and kids do not have to abandon school because it is too far away or unreachable.
   2. This ultimately means that *infrastructure is key* to the effectiveness of policies that aim to *improve schooling and health care*.
      1. Without infrastructure, those policies will not be effective at all.

**But the problem with improving infrastructure is:**

1. It is *very expensive*.
   1. Developing countries tend to not have enough money to invest into roads and things.
2. It is a supply side policy so it *may take years for the effect to be displayed*.


### 4. Taxation

Tax revenue is also called *fiscal dividends*.

**Taxation can actually hinder economic development and growth:**

1. There may be high levels of **corruption**, meaning the tax revenue is not being used to help the public, and rather goes to politician pockets instead.
   1. This is was a big problem with India, there was corruption at the highest levels of government but after 2014, the newly elected government have almost completely eliminated the corruption at the top.
2. Tax exemptions may be given to corporations that work closely with the government, this is another form of corruption.
3. Since there is typically *low corporate activity* in developing countries, the government often gives **tax incentives** to TNC's to start production there.
   1. This means the government cannot raise taxes on those TNC's as they have promised not to, decreasing the level of tax revenue they could be earning.
4. Developing nations also have large **informal markets**, and with informal markets, it is very difficult to collect any tax revenue.
5. Thanks to **the WTO**, tariffs (and protectionist measures in general) have been falling.
   1. Tariffs happen to be a very good source of tax revenue for the government.

### 5. Appropriate use of technology


1. It is important for the economy to harness and **use technology appropriately**.
   1. An example of this is solar cookers. These cookers can harness the sun in very hot countries to cook food, which is cheaper and more sustainable in the long run than using gas.
2. It is also important to try **using technology that have synergies with your country**.
   1. This means using technology that will not be hindered by your country's conditions, such as using solar panels in the Arctic circle.
3. **Weather based technologies** are also a good usage of technology.
   1. In India, farmers are using technologies to help them predict the weather, this then allows them to plan for predicted weather.
   2. This then greatly improves agricultural productivity and economic growth.

### 6. Female equality

If women are placed on the same footing as men, then it can greatly help development of the economy.

**Why is female equality important to development?**

1. Women with children will be able to **improve their children's health**.
   1. This may come in the form of vaccinations, better nutrition, etc.
   2. This will then reduce infant mortality and help drive down fertility rates.
2. Women in education will know that education is important, so **they will promote education** to their own families.
   1. This leads to higher incomes for the family and better development overall.
3. Women make up 50% of the population, so having 50% more people in the work force will lead to **economic growth and lower unemployment**.
   1. This then leads to higher national incomes and better standards of living.
4. Women may want to have **smaller families**.
   1. This is because if they want to send their kids to good universities, they understand that it is better to have fewer kids (more economically viable).
   2. Rising incomes also seems to have an inverse correlation with the fertility rate.

### 7. Income distribution

If income is very unequally distributed then it may create problems for the development of the country.

**Why is unequal income distribution bad for development?**

1. If people do not get a good amount of income, then it will lead to a **lack of savings**.
   1. This then prevents investment from taking place.
2. In developing countries, the richer people tend to be *bureaucrats and politicians*, meaning they will enact policy to keep themselves rich, and not really care about the poor.
3. **Capital flight** may also occur, since rich people have a lot of money thanks to unequal income distributions, they may then send it *out* of the economy.


## Political Stability

In developing countries, political stability is very important for the overall development of the country.

### The benefits of political stability:

1. There is a higher chance of **FDI** into the country
   1. This is because firms know that there is no corrupt bureaucracy in the country that will hinder their profits
   2. There is no unnecessary regulation and very little red tape.
2. If the country requires **aid**, then they are more likely to get it because people know the government is stable and trust worthy.
3. If politicians are put into power through **democracy**, then they will ensure that they keep on doing things that are good for the people to ensure they are still in power.
   1. This is the benefit of democracy.

### Negatives of political instability:

1. There may be a **loss of infrastructure**.
   1. This may be due to civil conflict and war.
2. There is also a **loss of investment**, because investors will be afraid to put their money in an unstable country.

**A major threat to development is *corruption***, which may manifest itself in a multitude of ways:

1. **Inefficient regulations**: This is when corporations are not following regulations and the government turns a blind eye to it.
2. **Reduced FDI** flows due to foreign investors not willing to risk dealing with a corrupt government.
3. **Bribes**: Businesseses may have to pay bribes to expand their business, which in turn raises their costs of production.
4. Projects given to the **highest bidder**, rather than the *most efficient producer*.
5. **Legal corruption**: Laws may not be properly enforced and the judicial system may not be very effective as they are corrupt.

**This ultimately leads to government failure, and a misallocation of resources.**

# Quantitative Easing

## Why is quantitative easing used?

It is used when traditional approaches to monetary policy fail to increase aggregate demand.

1. Used when low availability of credit
2. Low consumer/ business confidence
3. Banks are not very willing to lend out money

**How does quantitative easing work?**

1. The central bank creates money electronically.
2. That money is used to buy *financial assets* from financial institutions.
3. The price of government bonds *increase*, and the yield of those bonds *decrease*.
4. Financial institutions now have lots of money, this means they may start loaning this money out, or invest in shares/ corporate bonds.
5. All of this stimulates borrowing, spending and incestment, leading to increased AD and therefore increased growth.




# Micro Finance

**What is micro finance?** The distribution of small loans to individuals entrepeneurs or groups of people to stimulate business activity, profits and incomes.

## What Are The Benefits Of Micro Finance?

1. It helps **fill the savings gap**
   1. This is because it allows people to acess finance and grow their businesses
   2. Traditional banks would likely charge high interest rates or maybe not give credit to these people because they will not want to take the risk (as the banks do not have acess to very much money to hand out).
2. It **can relieve poverty** by allowing smaller businesses to expand and earn higher incomes.
3. It is a source of finance **without huge interest rates**.
   1. This means small businesses won't be in debt of huge amounts of money.
4. It can help **empower women**.
   1. This can be hugely beneficial in development of the economy.

## What Are The Problems With Micro Finance?

1. Lots of **businesses fail**
   1. So how do the loans get paid back?
2. Lenders can still apply **exorbitent interest rates** and bully the borrowers.
   1. Over the recent years, the scheme has seen problems of lenders behaving more like loan sharks than traditional lenders.
3. **Loans may not be big enough to alleviate poverty**.
   1. This is because in developing nations, private firms handle a lot of sectors of the economy which the government does not have enough funding for, such as schools.
   2. This then means the person who was given the loan, may actually spend a lot of it on school, health, etc.
   3. This means that a lot of the money is being *used for consumption*, rather than for investment.


# Long Run Strategies To Develop A Country

These are strategies to increase the quantity, and or quality of the factors of production in the country.

Long run strategies are *more sustainable* than short run strategies.

## Natural Resources

1. Using **fertiliser** to maximise land efficiency during agricultural use.
2. Improving **agricultural technologies**.
   - This may come in the form of investing in new machines, or tractors, but improved technology leads to improved productivity.
3. **Building upwards** means you can use the land you have more effectively.


## Improving Human Capital

1. **Slowing the population** may be effective, such as giving contraceptives to people.
   - Very high population growth actually hinders development in developing nations.
2. Improving **health and education** will boost productivity.
3. Supply **vocational training** for the jobs that the economy needs, such as plumbing.

## Improving Capital & Technology

1. Increasing the **quantity of capital**.
   - The problem with developing nations trying to increase the quantity of capital in the economy is that there is a lack of funding.
   - The government is likely to not have very much money, and there is probably a low level of savings in the economy.
   - There may even be a foreign currency gap.
2. **Improving technology**, especially in the key industries of a developing country such as agriculture.
   - This arguably may be more important than increasing the levels of capital in the economy, as efficient technology usage is easier for a country to do.

## Improving Institutions

1. A **stable financial system** must be in place to facilitate saving and borrowing in the economy
2. There must be a **good legal system** and strong property rights.
3. **Schools and hospitals** must be available to ensure the population is well trained and healthy.
4. **Key infrastructure** such as roads and bridges must be present.


# Trade & How It Can Help Development

## The Benefits Of Trade:

**Remember the 4 macro-economic objectives and always link back to them.**

1. Countries can **exploit their comparative advantage** and specialise in those goods.
   - Developing nations are normally resource rich, and they can export those goods.
   - Over the years, the demand for natural resources have been increasing, and so prices have also been increasing, which is great for a resource rich country.
   - This increases export revenue, which leads to increased *aggregate demand*.
   - Increases to growth also leads to increased economic development.
2. Opening up your markets allows consumers to **benefit from lower prices and greater choice**.
   - Another point to make is that increasing trade with a country will often lead to improved *political relations*.
   - A good example of this sub-Saharan nations and China.
3. **Economies of scale benefits** as the firms in your nation will have access to a massive world-wide market, which will allow them to make greater output.
   - Your firms will also likely become *more productively efficient* as they have to compete on prices with international firms.
   - This will lead to higher profits for firms and then may lead to increased government tax revenue.
   - That increased tax revenue can be spent on public sector spending, such as long run strategies for growth (investment into human capital, etc).
4. **Technological transfers** can take place, which is vastly beneficial as your firms can copy technology from abroad, which will lead to improved productivity and other benefits.
   - Technology is also very important in allowing an economy to develop past agriculture, and move onto manufacturing or other industries.  

## The Problems With Trade

There are some problems with adopting trade as a strategy for development.

1. **The resource curse:** A lot of countries rely on primary commodities, which has some problems.
   - Falling prices leads to lower export revenue
     - Lower export revenue leads to falling national income
     - This then leads to workers having their wages cut, or being fired altogether.
     - This then leads to less growth in the economy, higher unemployment, and a worsening of the current account.
   - Natural resources tend to be finite in quantity, so relying on exporting these resources for growth is *unsustainable.*
   - If the resource becomes obsolete (due to technological improvements), then demand for these commodities will plummet.
     -  This can lead to structural unemployment as the economy was built around exporting those goods 
     -  The economy may then go through a recession. 
2. Primary commodities are very **susceptible to price fluctuations**.
   - This is because their demand tends to be very price inelastic because there are little substitutes, and at the same time, *supply* is also price inelastic (takes a long time to produce crops, or oil so they cannot respond to changes in demand very quickly).
     - If demand and supply are both price inelastic, that means any shifts of the two curves will create *huge* changes to price.
     - Since the primary commodities market is world-wide, that means if any country has had a very big boost to their productivity, the increase in supply will lead to a massive decrease in price for that good *internationally.*
   - Fluctuating prices is not good for the economy in the long run as it is hard to predict revenue, export revenue, demand and there will be a high level of instability of national income.
3. **Access to international market may be limited** meaning developing countries may not even have the chance of selling their exports to other countries.
   - This may be due to *protectionist* measures, such as the US subsidising corn production. These subsidies lead to foreign exports being *less price competitive*. This is an "import substitution" strategy.
   - Another form of this protectionism can be seen in the EU, in the form of a common external tariff that all EU nations place on non-EU countries, and also extremely high regulations and standards. 
   - Tariff escalation is when higher tariffs are placed on manufactured goods, rather than primary goods. This then means developing countries have less of an incentive to move away from producing primary products
  - Developing nations also tend to have non-convertible currencies, which mean the currencies are often very difficult to trade for other currencies, and that means developing countries may not want to import goods from there because *they can't get any of the developing nations currency*
    - Another problem is that developing countries often have currencies that fluctuate quite a lot, this means firms from abroad are more reluctant to buy a lot of the currency as *it may potentially fall in price*.
    - This leads to difficulty in long term trading.
4. There may be a **long term decline in the terms of trade** for developing countries, if they *are exporting primary commodities* (refer to Prebisch-Singer hypothesis for more information).
   - This means export prices relative to import prices *fall*. In other words, your exports are very cheap and your imports are very expensive.
   - This then leads to difficulties sustaining long term development as the country experiences *falling export revenue* (their exports are cheaper and imports are more expensive). 
     - Imports are more expensive therefore it may lead to cost push inflation, as importing capital from abroad is more expensive.
     - Rising inflation relative to other countries leads to a further decline of the terms of trade, and an *overall decline in standards of living.*


# The Prebisch-Singer Hypothesis

**The Prebisch-Singer hypothesis says that** there will be a *long run* decline in the terms of trade for countries that depend on natural resource exports.

**To work out the terms of trade for a country you do:** 
\begin{huge} $\frac{IndexOfExportPrices}{IndexOfImportPrices} \times 100$ \end{huge}

**What causes the terms of trade to decline?**

1. The demand for primary commodities is **income inelastic.**
2. The demand for *manufactured* goods however, are **income elastic.** As income goes up, so does the demand for them.
3. This means, as incomes of developing nations (who export primary commodities) go up, they will demand a lot more manufactured goods.
4. This then pushes up the price of manufactured goods (the goods they want to import), and since their own exports (primary commodities) are demand income *inelastic*, the prices of their exports will not rise very much as incomes go up.
5. Therefore, in the long run as the world gets richer and richer, the prices of manufactured goods will sky rocket, while the prices of primary goods stays relatively the same.
6. This then means the terms of trade for countries that export primary goods will *decrease*, as their import prices are much higher than their export prices.
7. This ultimately means that the developing country has to export *more* of their exports to fund their imports.

This leads to a decline in the standards of living for developing nations in the long run, but in the short run they will improve.


**How can a country prevent the terms of trade from declining?**

1. Developing countries will enjoy a boost to their terms of trade in *the short run* only.
2. This means, in the short run they should aim to diversify the economy.
3. They can use their export revenue from primary products to invest into new industries, and therefore prevent their terms of trade declining in the long run.


# Policies To Promote Trade & Development

The short run goal is to earn export revenue and increase growth, but the long run goal is to try *breaking away* from primary product dependence.

## Import Substitution (To Industrialise)

**What is import substitution industrialisation?** The idea with this policy is to place tariffs on imported manufactured goods, to allow domestic manufacturing industries to grow.

**What are the benefits of import substitution?**

1. Protects domestic jobs
2. Protects the economy from foreign influences and from potential dominance of TNC's in the economy
  - This means your country will not be held at the mercy of TNC's, instead it will your own domestic firms that control the economy.

**What are the problems of import substitution?**

1. In the short run, there will be good benefits of job creation, but in the long run, there will be **problems to long run growth**.
   - This may be because import substitution leads to a decrease in imports of capital from abroad
   - Also, if the industry is not internationally competitive in the long run, then it will lead to the industry being out competed, and therefore unemployment will increase.
2. It is going **against the idea of *comparative advantage***. This is because you are trying to grow an industry that may not actually have a comparative advantage, which leads to very low efficiency in the long run.
   - Lack of efficiency leads to higher prices for consumers
   - Specialisation gains will be lost, and there will be less incentive for an industry to become more efficient if it is being protected.
3. There may **retaliatory protectionism** placed on you
   - This means your export revenue will fall, lowering growth.

## Export Promotion Strategy

This is when you *don't* place any protectionism and allow your firms to compete with the global market and let the market handle itself.

Export promotion entails:

1. Removing all protectionist measures from the economy
2. This then promotes trade, growth, and job creation in the economy.
3. This then leads to higher GDP, higher incomes for people, and eventually higher levels of development.

**What are the benefits of export promotion?**

1. Developing countries can exploit their **comparative advantage** in primary products (in the short run).
2. Increased revenue's and profits from trade can then be **invested into developing capital** and technology.
   - This then makes it easier for them to develop out of primary product dependence, and help advance the economy.

**What are the problems of export promotion?**

1. Although you are allowing for free trade, **other countries may still place protectionist measures** on your country and exports.
2. There may be **higher levels of income inequality**
   - Some industries in your economy may grow but the benefits of that growth may not be spread to the entire economy
     - Free market economists may argue that although inequality may be high in the short run, the benefits and money will trickle down into the rest of the economy in the long run
3. The over-dominance of **TNC's**
   - Free global trade may attract lots of TNC's to come into the country, this may lead to them having too much power and control over the economy.  

## Trade Liberalisation

Trade liberalisation includes:

1. Promote fiscal discipline by reducing government spending
2. Promote deregulation, and privatisation
3. Promote trade liberalisation by reducing protectionist measures
4. Allow exchange rates to run freely
5. Remove any non-tariff barriers from the economy
6. Essentially, allow the free market to work freely.

**What are the benefits of trade liberalisation?**

1. There will be a **better allocation of resources** in the economy.
   - There will be less risk of market failure.
   - This then leads to more sustainable growth as the markets will be allocatively efficient.
   - This is great for the whole economy.
2. Allows for the economy to be more stable as there is no government intervention
   - This will promote FDI flows into the country
   - It will promote investment as firms are more confident in the stability of the economy
   - This all leads to higher incomes and more job creation in the economy.
3. Although there may be income inequality in the short run, in the long run there will be a trickle down effect and the money will be spread throughout the economy.

**What are the problems with trade liberalisation?**

1. In real life, more poverty has been created thanks to trade liberalisation
   - TNC's have gone into countries with very low levels of regulations and have exploited the workers there by paying low wages and making them work in bad conditions.
   - This has lead to higher income inequalities in the country.
   - TNC's have also created higher levels of pollution in the country, which is a negative externality and a market failure. 
2. Fiscal discipline and spending cuts may sound good on paper, but if there are cuts to education and health care then it may lead to a decrease in economic development.


## Bilateral Trade Agreements & Regional Preferential Trade Agreements

**What are the benefits of bilateral trade agreements & PTA's?**

1. This allows for more market access for firms in those countries.
   - It may lead to lower transport costs as countries in the same region can then work together and allow for free trade access in and out of the country.
2. Another benefit is that there will be greater specialisation gains.
   - If there is a group of countries in a regional preferential trade agreement, then each country can focus on producing what they are good at producing and then export/ import with one another.
   - This allows them to specialise, and grow their key industries.


**What are the problems with bilateral trade agreements & PTA's?**

1. If the group of countries export the same type of goods, this means the trade will not be very beneficial to any of the countries inside the trading region.
   - If the members of the group imposed a common external tariff on goods from outside the group, then the problem will become even worse.
   - This is because since the members in the group all export the same things, that means they **have** to import from outside the group.
   - Since there are tariff's placed on goods from outside, that leads to high import costs. 
2. Preferential trade agreements often place common external tariffs on goods from outside the group, that means any goods you need to import will become *more expensive*.
3. There may also be greater trade barriers placed on your country outside of the PTA you are a member of, leading to your exports becoming more expensive in those countries that have placed the trade barriers.
   - This limits your scope of growth.


## Diversification Of The Economy

This is mainly used to move away from primary product dependency and try advancing the economy into producing manufactured goods, etc.

**What are the advantages of diversification?**

1. It will limit the problems associated with primary product dependence, and eliminate the resource curse problems.
2. There will be an increased level of technology by moving away from primary products.
   - This then leads to more job creation and higher economic productivity in the country.
   - It may also lead to an increase in the level of skills in the economy, this is because primary product extraction does not require very many skills, while manufacturing does.

**What are the problems with diversification?**

1. There is the problem of **tariff escalation.**
   - Tariff escalation is when higher tariffs are placed on manufactured goods, in comparison to primary goods.
   - This means the incentives to move away from primary product dependence decreases, as there will be higher tariffs on any manufactured goods you may produce.
2. Moving away from primary good's requires **highly skilled workers**
   - This means if the level of education in the economy is not very high, then the economy may not be able to move away from primary good's. 


# FDI & It's Role In Development

## Why do foreign firms invest into developing countries?

1. Developing countries may be **abundant in natural resources**.
2. Firms can expand their market size by investing into **newly emerging economies**.
   1. This increases their potential of growth.
3. It may be **cheaper to produce goods** in those countries, thanks to lower labour costs.
4. There tends to be **less regulation** in developing countries.


## What are the benefits of FDI?

1. Investment into the economy is an **injection into the circular flow of income**.
   - This leads to higher employment, leading to increases in potential growth for the economy.
2. Higher employment also increases incomes in the economy, which can **fill the savings gap**.
   - Higher savings can then facilitate investments in the economy.
3. There will be a **positive effect on the capital account** in the Balance of Payments.
4. TNC's can **develop infrastructure** in the developing country.
   - An example of this is Chinese firms in African countries.
   - They help develop infrastructure in these African countries.
5. Workers that are employed by the foreign firms will be trained by them and be **more productive**.
   - This is great for the economy in the long run as those skilled workers can then start up their own firms.
6. The potential for **technological transfer** is very high.
   - The developing country is then exposed to much better technology, which is great for the economy.
7. There will be **higher tax revenues** for the developing country as there will be more business there.
   - TNC's will have their profits taxed.
   - Any goods that are sold in the economy will also be taxed (VAT), thereby increasing tax revenues even more.

## What are the potential costs of FDI?

1. Employment may be **short term**.
   - There is no guarentee that TNC's will continue operating in the country.
   - Also, there is no guarentee that TNC's will even use the labour force in the developing nation.
     - They may prefer bringing their own workers instead.
2. TNC's may have **too much power** in the economy.
   - They may have power over politicians, and therefore may be able to get massive tax excemptions.
   - They can also engage in corrupt activities such as bribery.
3. TNC's may invest into **labour saving technology** (such as machinery), rather than employing people.
   - This means employment may not increase very much.
4. TNC's may strip natural resources and then just leave.
   - They may buy resources cheaply and then send them back to their own country, which is not good for the developing country.
5. There may be environmental costs (which are negative externalities).
   - This can lead to resource depletion, and pollution.
   - Since foreign firms are profit maximising, they will pay no regard to the environmental costs associated with their production.
6. Tax revenue may be lower than expected.
   - This is because tax incentives are often given to firms to promote production.
   - Foreign firms may also find tax loopholes to not pay very much tax.


# Sustainable Development

**What is sustainability?** Sustainability is meeting the needs of the present without reducing the ability of future generations to meet their own needs.

## Sustainable Growth

1. Profits can be **reinvested** into improving the quality of capital, and the quantity of capital.
   - This can be done by research and development into new technologies, and new innovative methods of production.
   - This then leads to an increase in the capital stock of an economy, which is *long run* growth.
2. The **fiscal dividends (tax revenue)** recieved from growth can be spent on education, health care, roads, and infrastructure.
   - These are all supply side policies which will lead to long run growth of the economy.


## Unsustainable Growth

1. Pursueing growth may lead to **resource depletion** and resource degradation.
   - This may lead to a lack of resources in the economy for the next generation.
   - Resource degradation is also a big problem where production can lead to other resources in the economy being damaged, such as chemicals in the soil.
   - All of this also leads to lower levels of happiness in the economy.
2. Deforestation is also unsustainable and creates lots of **negative externalities**.
   -  Examples of some negative externalities are soil erosion, loss of bio-diversity and higher risks of flooding.
3. The **over-use of fossil fuels** in the economy
   - This can create negative externalities such as pollution.
   - Pollution will harm people in the country, leading to lower levels of healthiness and therefore will also probably decrease the levels of productivity in the economy.
 

# Other Strategies For Development

## Foreign Aid

**What is the aim of foreign aid?** Aid is meant to fill the savings gap in developing countries and promote economic development.

**What forms of aid are there?, and how do they help?**

1. **Long term loans:** These are often loans with very low interest rates, and are paid back over a very long time.
2. **Tied aid:** This is when aid is sent to a country, but with the conditions that the reciepient country only buys goods and services from the donor country.
3. **Project aid:** When money is given for the key objective of developing infrastructure.
   - The World Bank gives lots of project aid.
4. **Technical aid:** When money is given to advance technology in the economy.
   - It may be used to subsidise research and development in the country.
5. **Commodity aid**: When money is sent to allow the recipient country to buy commodities to lower costs of production, aiding growth, and thereby improving development.

**Bilateral aid** is aid from one country to another.
**Multi-lateral aid** is aid that is diverted by an international organisation such as the World Bank, and they will then decide on who gets the aid money.

**What are the problems with aid?**

1. **Corruption**: The government may not spend the aid money on the welfare of their citizens.
2. **Dependency on aid**: Countries and firms may become dependent on aid to lower their costs, reducing their incentives to innovate.
3. **Aid weariness**: This is when advanced economies no longer want to give aid because they are suffering from their own economic problems.
4. **Income inequality**: This can be caused by aid money being spent on industrialisation, which normally only benefits a few.
5. The aid may be used for **political agendas**, rather than development.

## The Lewis Model For Industrialisation

**What is the Lewis model?** 

1. The Lewis model says that developing country's have dual economies. One economy is the low productivity agricultural sector, and the other is the industrial sector, with high levels of investment.
2. Lewis believed that people from the agricultural sector could be attracted to come and work for the industrial sector by higher wages.
3. He also believed that the productivity of the agricultural sector was so bad, that people leaving the agriculture sector of the economy would have little to no impact on the GDP of the economy.
4. This means, as more people joined the industrial sector, their incomes would rise. Rising incomes leads to increased savings.
5. Thus, growth could be achieved from rural to urban migration.

**How can the Lewis model increase development?**

T government can build factories to encourage the transition from an agricultural economy to an industrial one.

## Buffer Stock Schemes

**What is a buffer stock scheme?** A buffer stock scheme involves imposing a maximum and a minimum price for goods.
- When there is *excess supply* for the good (thanks to the minimum price), the government buys up the excess.
- When there is *excess demand* for the good (thanks to the maximum price), the government sells off their own supplies.

**When are buffer stock schemes used?**

Buffer stock schemes are normally used on commodities, as they often have volatile prices.

**What are the benefits of a buffer stock scheme?**

1. It can help stabilise prices for key commodities in the economy.
   - This promotes investment as investers can plan ahead (in the long term). 
2. It prevents sharp contractions in price
   - This prevents producers from suffering massive losses in revenue
3. It prevents sharp increases in price
   - This helps consumers afford the good 


**What are the problems with buffer stock schemes?**

1. It requires the stocks to both go *up*, and also *down*.
   - If the stocks keep increasing (government keeps buying more), then the scheme will run out of money.
   - If stocks keep shrinking (government keeps selling), then the scheme will run out of stock.
2. Buffer stock schemes require huge amounts of initial investment.
3. There may be information failure regarding the maximum price or minimum price.
  - Very high minimum pricing will lead to producers becoming less dynamically efficient, as they no longer have to cut costs to keep profits high (thanks to the minimum pricing on their good).


## Development Of Tourism

**What are the benefits of development using tourism?**

1. Tourism is demand *income elastic*, meaning the demand for tourist vacations increases as incomes do.
  - This means as the world develops, country's that have a tourism industry will experience higher demand, therefore increasing their economic growth.
2. Tourists can fill the foreign currency gap.
  - This foreign currency can be used to finance imports or finance capital purchases from abroad.
3. TNC's are likely to invest into the industry too, which brings FDI flows and improved infrastructure (TNC's have to ensure there is a reliable supply of electricity, water and other things).
4. Jobs can be created locally and the jobs don't require specialist training.
5. The government will enjoy higher tax revenues.


**What are the problems with developing a country using tourism?**

1. The tourism industry is seasonal.
2. Workers are often low-skilled, and not paid very much, this limits the scope of further development.
3. TNC's that have invested into the industry will often repatriate their profits.
4. There may be a large number of externalities involved in developing the tourism industry.
  - This may include pollution, environmental damage, and the impacts on local culture.


## Fair-trade Schemes

**What is fair trade?** Fair trade products are products that have worked together with their producers to ensure:

1. A fair price was paid to producers
2. There is community development
3. The working conditions are fair
4. The environment is protected and not harmed.





# Evaluating Different Strategies For Growth

## Market Based Strategies

**What are some examples of market based strategies?**

1. Promoting **FDI** into the country.
2. **Privatisation** of certain industries.
3. **Deregulation** of industries.
4. **Trade liberalisation** by taking away protectionist measures.
5. **Reducing the size of the government**
6. **Removal of government subsidies**.
7. **Floating exchange rate** systems.
8. **Micro finance** schemes.


### What are the benefits of market based strategies?

1. Free market economists argue that there is **a more efficent allocation of resources** in a free market.
   1. This is because government intervention can distort the price signal.
   2. Another reason is that a lot of government intervention leads to government failure, such as corruption and excessive red tape.
2. They also argue that **free markets promote competition** and the profit motive will mean that firms will invest to be dynamically efficient.
   1. This is so that their costs can decrease and then they will be able to earn higher levels of profits.
   2. Firms also want to supply what consumers *demand*, and firms will know what consumers want much more than the government, which means allocative efficiency.
   3. Economists will argue that state run firms are very x inefficient, as they have no profit motive, so they have no reason to cut costs.
3. It also **encourages FDI**
   1. This is because firms know that there won't be any red tape, no unecessary regulations, and no corruption as there is very little government intervention.

### However, what are the problems with market based strategies?

There are some problems with allowing markets to run freely.

1. Will there be **infrastructure developments?**
   1. Private sector firms are less likely to develop these projects
2. Free markets **may not efficiently allocate resources at the social optimum levels**
   1. This is because public goods will have a *missing market*, and merit goods may be *under-produced*, while demerit goods may be *over-produced*.
   2. Important sectors of the economy such as education, health care and defence may not be allocated the right amount of resources in a free market.
3. There may be **market failures**, such as environment problems.
   1. Resource depletion, pollution, and other negative externalities reduce social welfare in the economy.
4. **Income inequality** tends to increase in a market economy.
   1. Without any government support and intervention, people on lower incomes will have no safety net to help them if they are unemployed, or disabled.
5. **Protectionism in advanced economies** may limit your growth as their markets are not freely accessible.
6. A **lack of well-functioning financial institutions**.
   1. This means there won't be places where people will deposit their savings in, and that leads to a savings gap.
   2. Therefore we may need government intervention to ensure there are financial institutions present for consumers to use.


## Interventionist Strategies


**What are some examples of interventionist strategies?**

1. **Import substitution**: When governments try switching consumer demand from imports to goods that are domestically produced.
2. **Protectionism**
3. **Exchange rate manipulation**
4. **Regulations**
5. **Nationalisation**
6. **Increased government spending**
7. **Buffer stock schemes**
8. **Infrastructure projects**
9. 

### What are the benefits of interventionist strategies?

1. Private firms are unlikely to **develop infrastructure,** therefore government intervention will be necessary to ensure infrastructure is made
   - **Public goods** will also be provided by the government rather than having a *missing market*
2. The government is a **major employer** in the public sector
   - They can spend money on developing human capital in the economy.
3. The government can ensure there is a **stable economy**.
   1. This promotes growth and development, and FDI is more likely to come in.
4. The government can ensure there is **welfare** available for those who need it, such as pensions or disability benefits.


### What are the problems with interventionist strategies?

1. Bureaucracies tend to be **inefficient**.
   - There is a higher chance of corruption.
   - This is a very inefficient allocation of resources.
2. Nationalised industries tend to be **x inefficient** as they *have no profit motive*.
   - This means they will be operating inefficiently, especially compared to a private firm.
3. Government spending leads to **massive debts**.
   - This can then hold back development even further.
   - Countries may want to start printing out money to pay off their debt, this just leads to economic catastrophe and hyper-inflation.
     - An example of this is Venezuela, or Zimbabwe.
4. Government spending can cause the **crowding out effect**.

     \vspace{0.35\textheight}

   -  The government often *borrows* money to finance its expenditure, they do this by issueing out government bonds.
   -  If they need to finance a project, then that means they will increase their demand for people to buy their government bonds, which will raise the interest rates for their bonds (they are willing to pay more to borrow).
   -  Since most interest rates in the economy are based on the interest rates of government bonds (such as mortgages, etc), that will drive up interest rates in the economy as a whole.
   -  Higher interest rates in the economy make it more expensive for firms to borrow money, and therefore decrease investment.
   -  Decreased investment can lead to decreased aggregage demand, which may hinder growth in the economy.


\begin{large}
Government intervention can be very beneficial as long as these problems are taken care of. \end{large}











\newpage 

# Public Expenditure

**Current Government Expenditure:** Government spending which recurs.
- This may include drugs for the NHS.

**Capital government expenditure:** Spending by the government on assets, such as building houses.


**Transfer payments:** Welfare payments from the government.
- No goods or services are transacted in this, it is a direct transfer of money from the government to someone.


## Reasons for the changes in public expenditure:

1. The UK government spends most of its budget on pensions and welfare benefits, followed by health and then education.
2. As the economy grows, government expenditure also tends to grow. This is because the government enjoys higher tax revenues.
3. Countries with ageing populations have to increase expenditure on pensions.


